#!/usr/bin/env bash
# This script configures a Ubuntu server with below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp -f /etc/hosts ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
sed -i 's/^127\.0\.0\.1\(\s*\)localhost$/127.0.0.2\1localhost/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
