#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it’s executed on.


# Retrieve IPv4 addresses using ifconfig and filter out the active IPs
active_ips=$(ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}')

echo "$active_ips"
